#!/usr/bin/env python3
"""
Convert a raw .bin into a C header that embeds the bytes as a const array.

Usage:  emit_blob_header.py <input.bin> <output.h>
"""
import sys, os

if len(sys.argv) != 3:
    print(__doc__, file=sys.stderr)
    sys.exit(2)

src, dst = sys.argv[1], sys.argv[2]
with open(src, 'rb') as f:
    data = f.read()

lines = []
lines.append('/* AUTO-GENERATED by flashloader/emit_blob_header.py - do not edit by hand. */')
lines.append('/* Source: ' + os.path.basename(src) + ' ({} bytes) */'.format(len(data)))
lines.append('#ifndef __L0_OB_LOADER_BLOB_H')
lines.append('#define __L0_OB_LOADER_BLOB_H')
lines.append('')
lines.append('#include <stdint.h>')
lines.append('')
lines.append('static const uint8_t l0_ob_loader_blob[] = {')
for i in range(0, len(data), 12):
    chunk = data[i:i+12]
    lines.append('  ' + ', '.join('0x{:02x}'.format(b) for b in chunk) + ',')
lines.append('};')
lines.append('')
lines.append('#define L0_OB_LOADER_BLOB_SIZE       ((uint32_t){})'.format(len(data)))
lines.append('#define L0_OB_LOADER_LOAD_ADDRESS    (0x20000000UL)')
lines.append('#define L0_OB_LOADER_ENTRY_ADDRESS   (0x20000001UL)  /* Thumb bit set */')
lines.append('#define L0_OB_LOADER_PARAM_ADDRESS   (0x20000100UL)')
lines.append('#define L0_OB_LOADER_STACK_TOP       (0x20002000UL)')
lines.append('')
lines.append('#endif')
lines.append('')

with open(dst, 'w', newline='\n') as f:
    f.write('\n'.join(lines))

print('Wrote ' + dst + ' (' + str(len(data)) + ' bytes embedded)')
