#!/usr/bin/env python3
"""
Convert a raw .bin into a C header that embeds the bytes as a const array.

Usage:  emit_blob_header.py <input.bin> <output.h> [array_name] [macro_prefix]

array_name   : name of the const uint8_t[] (default: l0_ob_loader_blob)
macro_prefix : prefix for the SIZE/ADDRESS macros (default: L0_OB_LOADER)
"""
import sys, os

if len(sys.argv) < 3 or len(sys.argv) > 5:
    print(__doc__, file=sys.stderr)
    sys.exit(2)

src, dst = sys.argv[1], sys.argv[2]
array_name = sys.argv[3] if len(sys.argv) >= 4 else 'l0_ob_loader_blob'
macro_prefix = sys.argv[4] if len(sys.argv) >= 5 else 'L0_OB_LOADER'

with open(src, 'rb') as f:
    data = f.read()

guard = '__' + array_name.upper() + '_H'

lines = []
lines.append('/* AUTO-GENERATED by flashloader/emit_blob_header.py - do not edit by hand. */')
lines.append('/* Source: ' + os.path.basename(src) + ' ({} bytes) */'.format(len(data)))
lines.append('#ifndef ' + guard)
lines.append('#define ' + guard)
lines.append('')
lines.append('#include <stdint.h>')
lines.append('')
lines.append('static const uint8_t ' + array_name + '[] = {')
for i in range(0, len(data), 12):
    chunk = data[i:i+12]
    lines.append('  ' + ', '.join('0x{:02x}'.format(b) for b in chunk) + ',')
lines.append('};')
lines.append('')
lines.append('#define {}_BLOB_SIZE       ((uint32_t){})'.format(macro_prefix, len(data)))
lines.append('#define {}_LOAD_ADDRESS    (0x20000000UL)'.format(macro_prefix))
lines.append('#define {}_ENTRY_ADDRESS   (0x20000001UL)  /* Thumb bit set */'.format(macro_prefix))
lines.append('#define {}_PARAM_ADDRESS   (0x20000100UL)'.format(macro_prefix))
lines.append('#define {}_STACK_TOP       (0x20002000UL)'.format(macro_prefix))
lines.append('')
lines.append('#endif')
lines.append('')

with open(dst, 'w', newline='\n') as f:
    f.write('\n'.join(lines))

print('Wrote ' + dst + ' (' + str(len(data)) + ' bytes embedded)')
